### ISSUE TITLE
add todo example app with apollo

### ISSUE THREAD

**Issue by n1ru4l** [n1ru4l/graphql-live-queries#146]
In order to showcase and proof that `@n1ru4l/socket-io-graphql-client` works with apollo-client, adding the example app using apollo would be awesome :)

**Comment by Venryx** [comment]
I was looking through the Apollo example, and noticed that it uses socket-io-graph-ql-client, rather than the built in `HttpLink` (from "@apollo/client") and `WebSocketLink` (from "@apollo/client/link/ws").

Is it possible to use graphql-live-query without switching the Apollo client to use that socket-io-graph-ql-client?

If so, is there an example somewhere showing how to do so?

**Comment by n1ru4l** [comment]
@Venryx apollo-link-http does afaik not support not long living http connections such as SSE or chunked delivery https://github.com/graphql/graphql-over-http/blob/main/rfcs/IncrementalDelivery.md)

So you would have to write your own link that supports this (and use a server library that supports it).

When I started implementing graphql-luve-query the ecosystem around transports was not well developed. That is one of the reason why I created the graphql over sovket.io protocol which I also use for some of my applications.

Now we also have graphql-ws which also has full support for defer/stream and live queries.

You are not forced to use socket.io for the transport.

The graphql-ws protocol is probably better battle tested than my graphql over socket.io transport and most people should probably use graphql-ws .

I also do not recommend using the deprecated graphql-transport-ws (which is used by apollo-link-ws and apollo-server). Please use the stable and maintained graphql-ws package if you want to do subscriptions/live queries over websocket.

There is an example on how you can setup an apollo link that uses graphql-ws over here: https://github.com/enisdenjo/graphql-ws (this requires your server to also use the graphql-ws transport).

**Comment by Venryx** [comment]
Yes, it's odd to me that the Apollo team is still using `subscriptions-transport-ws`, since like you mentioned, it's no longer being maintained. I hope they will switch their codebase to `graphql-ws` soon. If they take too long, I will look into making the switch manually.

That said, I was able to hack together a solution with the existing vanilla Apollo setup/dependencies, without needing the [socket-io-graph-ql-client](https://github.com/n1ru4l/graphql-live-query/tree/main/packages/socket-io-graphql-client) package.

Server code: https://github.com/Venryx/postgraphile-live-query-demos/blob/02cc0bba79044180f61f8bfbcac55c0d2f3203b3/Server/Utils/LQHelper.ts
Client code: https://github.com/Venryx/postgraphile-live-query-demos/blob/a8323cba3c6acc3302e4fe291cf55057b79a68a5/Client/Utils/LibIntegrations/PGLink.ts

However, it is super ugly because I don't really know how to use "AsyncIterableIterator" generator functions. (for example, I just fiddled around with [my fake iterator wrapper](https://github.com/Venryx/postgraphile-live-query-demos/blob/a8323cba3c6acc3302e4fe291cf55057b79a68a5/Client/Utils/LibIntegrations/PGLink.ts#L75) [aka monstrosity] on the client-side until it did what I wanted)

That very hacky code appears to be working though; it's successfully generating json-patches on the server, and applying them on the client, with a vanilla Apollo setup. (I've confirmed using dev-tools that only patch data is being sent)

However, based on what you've said, it sounds like there are various negative side-effects of using the outdated `subscriptions-transport-ws` protocol. Is the issue that the connection will disconnect after some time, even if the user is still active?

Or maybe you mean something else by:
> apollo-link-http does afaik not support long living http connections such as SSE or chunked delivery

Are the limitations above show-stoppers? Or just not ideal?

(I would rather not change from the Apollo client's default transports and such unless/until I hit significant drawbacks with them.)

**Comment by n1ru4l** [comment]
How graphql-live-query and defer/stream are implemented on the "server"/executor is that the `execute` function which is used for executing mutations and query operations returns an AsyncIterator instead of a Promise (or sync value if no resolver is async).

If you want to implement the transport/executor on the server yourself you can use https://github.com/contrawork/graphql-helix, https://github.com/n1ru4l/graphql-live-query/tree/main/packages/socket-io-graphql-server or https://github.com/enisdenjo/graphql-ws as a reference.

I would however not recommend to do it yourself and rather pick one of those already existing solutions.

See https://the-guild.dev/blog/graphql-over-websockets or https://github.com/apollographql/subscriptions-transport-ws#graphql-ws on why you should not use subscriptions-transport-ws.

For Observable/AyncIterator/Sink interop I made this utility library: https://github.com/n1ru4l/push-pull-async-iterable-iterator It might be handy for your link. It also supports Safari iOS 14 which does not has Symbol.asyncIterator implemented.

**Comment by Venryx** [comment]
> If you want to implement the transport/executor on the server yourself you can use https://github.com/contrawork/graphql-helix, https://github.com/n1ru4l/graphql-live-query/tree/main/packages/socket-io-graphql-server or https://github.com/enisdenjo/graphql-ws as a reference.
>
> For Observable/AyncIterator/Sink interop I made this utility library: https://github.com/n1ru4l/push-pull-async-iterable-iterator It might be handy for your link. It also supports Safari iOS 14 which does not has Symbol.asyncIterator implemented.

Okay, I will take a look at both the demos and that interop utility, as I try to clean up and package the working code.

(For context, I'm attempting to create a helper package for [Postgraphile](https://github.com/graphile/postgraphile), utilizing [graphql-live-query-patch](https://github.com/n1ru4l/graphql-live-query/tree/main/packages/graphql-live-query-patch) to improve the efficiency of its live-query functionality, as [discussed here](https://github.com/graphile/graphile-engine/issues/725).)

> These are show stoppers as this does not allow to do subscriptions/defer/stream/live over http with the default http link (see apollographql/apollo-client#7691)

Ah, I see. The reason I haven't hit the issues yet is simply that I've only been using websocket-capable browsers, and so haven't hit the http-based fallback?

**Comment by n1ru4l** [comment]
> Ah, I see. The reason I haven't hit the issues yet is simply that I've only been using websocket-capable browsers, and so haven't hit the http-based fallback?

I can not follow 100%. AFAIK there is no Apollo link that uses a WebSocket transport with HTTP fallback.

If you are referring to the GraphQL over Socket.io transport (link): Socket.io tries to establish a WebSocket connection and falls back to a polling solution.

**Comment by Venryx** [comment]
> I can not follow 100%. AFAIK there is no Apollo link that uses a WebSocket transport with HTTP fallback.

Yes, my bad; the usage of httpLink and wsLink (as [seen here](https://github.com/Venryx/postgraphile-live-query-demos/blob/02cc0bba79044180f61f8bfbcac55c0d2f3203b3/Client/Utils/LibIntegrations/PGLink.ts#L43)) was for different things (regular queries vs subscriptions). The `wsLink` there is based on `@apollo/client/link/ws`, which is presumably based on the [subscriptions-transport-ws](https://github.com/apollographql/subscriptions-transport-ws) that you do not recommend.

I guess I'm wondering what is wrong with the [subscriptions-transport-ws](https://github.com/apollographql/subscriptions-transport-ws) library. Is it mainly just that its deprecated, and so will increasingly fall behind in features and stability?

**Comment by n1ru4l** [comment]
> I guess I'm wondering what is wrong with the subscriptions-transport-ws library. Is it mainly just that its deprecated, and so will increasingly fall behind in features and stability over time?

The reasons why I think you should not use it:
1. No active maintainers (200+ open issues https://github.com/apollographql/subscriptions-transport-ws/issues)
2. Deprecated
3. It has unnecessary dependencies (https://github.com/apollographql/subscriptions-transport-ws/blob/0cdf55b5f3f5ddca99f9a056ab5fa0cf94a66591/package.json#L12-L15)
4. Security concerns listed over here: https://github.com/enisdenjo/graphql-ws/issues/3

**Comment by Venryx** [comment]
Thanks. I'll keep those points in mind, and switch to another transport at some point (before production).

**Comment by Venryx** [comment]
By the way, I've finished published a working set of packages that add the json-patch/send-delta-only functionality between Postgraphile (backend) and Apollo (frontend): https://github.com/pg-lq/postgraphile-live-query

Discussion thread [here](https://github.com/graphile/graphile-engine/issues/725). (still needs a pull-request in postgraphile's upstream for easy installation)
